// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgK9xEjPFW8exJq7DKZ4DD6lrxZvkW4c',
    appId: '1:383863329314:web:39080507dfb34c0131f07b',
    messagingSenderId: '383863329314',
    projectId: 'hidden-terrain-368722',
    authDomain: 'hidden-terrain-368722.firebaseapp.com',
    storageBucket: 'hidden-terrain-368722.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9IONca9-NdfiD4twGy1OKQyeKrNQk0Fk',
    appId: '1:383863329314:android:34650a84c4b27b4d31f07b',
    messagingSenderId: '383863329314',
    projectId: 'hidden-terrain-368722',
    storageBucket: 'hidden-terrain-368722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMcIQBk8cA7RmnJhGqzCPQFNF7C1EAZ70',
    appId: '1:383863329314:ios:b77a154d66f6c49131f07b',
    messagingSenderId: '383863329314',
    projectId: 'hidden-terrain-368722',
    storageBucket: 'hidden-terrain-368722.appspot.com',
    iosBundleId: 'com.example.practiceflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMcIQBk8cA7RmnJhGqzCPQFNF7C1EAZ70',
    appId: '1:383863329314:ios:95e338993c79d63131f07b',
    messagingSenderId: '383863329314',
    projectId: 'hidden-terrain-368722',
    storageBucket: 'hidden-terrain-368722.appspot.com',
    iosBundleId: 'com.example.practiceflutter.RunnerTests',
  );
}
